### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by burkesquires** [jaywunder/otek#2]
Hi there,
The project looks cool so I thought I would try it out. I try the pip install and I get the following error:

FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/d7/8vn6rd1d6f37gtgy_13h3b95mx3fmv/T/pip-build-d65u0l4o/otek/dotOtek'

Thanks!

**Comment by junewunder** [comment]
fixing this now

**Comment by junewunder** [comment]
Okay this should be fixed now.  I was improperly including data files in the python package. I didn't fix the issue correctly, but I found a workaround

please close this issue if you can properly install the package.  Thank you!

**Comment by burkesquires** [comment]
Thanks! It works!
